name: Snapdrop
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.4+5

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  photo_manager: ^3.0.0
  flutter_svg: ^2.0.5
  qr_code_scanner: ^1.0.1
  socket_io_client: ^2.0.3+1
  flutter_launcher_icons: ^0.13.1
  receive_sharing_intent: ^1.4.5
  photo_manager_image_provider: ^2.1.1
  permission_handler: ^11.3.1
  lottie: ^3.1.0
  device_info_plus: ^10.1.0
  showcaseview: ^2.1.1
  shared_preferences: ^2.2.3
  introduction_screen: ^3.1.14
  shimmer: ^3.0.0
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.9
  firebase_crashlytics: ^3.5.6
  firebase_performance: ^0.9.4+6
  upgrader: ^10.3.0
  firebase_remote_config: ^4.4.6
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios : true
  remove_alpha_ios: true
  image_path: 'assets/logo/snapdrop_logo.png'
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/svg_asset/
    - assets/logo/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
        - asset: assets/fonts/Inter-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          style: normal
          weight: 300
