name: Snapdrop
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.5+6

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  photo_manager: ^3.6.4
  flutter_svg: ^2.0.5
  socket_io_client: ^3.0.2
  flutter_launcher_icons: ^0.14.3
  receive_sharing_intent: ^1.8.1
  photo_manager_image_provider: ^2.1.1
  permission_handler: ^11.3.1
  lottie: ^3.1.0
  device_info_plus: ^11.3.0
  showcaseview: ^4.0.1
  shared_preferences: ^2.2.3
  introduction_screen: ^3.1.14
  shimmer: ^3.0.0
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.0.0
  firebase_performance: ^0.10.0
  upgrader: ^11.3.1
  firebase_remote_config: ^5.0.0
  package_info_plus: ^8.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  qr_code_scanner_plus: ^2.0.10+1
  dropdown_button2: ^2.3.9
  animate_do: ^4.2.0
  flutter_blurhash: ^0.8.2
  glassmorphism_ui: ^0.3.0
  sensors_plus: ^6.1.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios : true
  remove_alpha_ios: true
  image_path: 'assets/logo/snapdrop_logo.png'
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/svg_asset/
    - assets/logo/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
        - asset: assets/fonts/Inter-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          style: normal
          weight: 300
