import 'package:flutter/material.dart';

import '../constant/theme_contants.dart';
import '../l10n/app_localizations.dart';
import 'step_badge.dart';

/// Present the "Where's the QR code?" help sheet — a dark modal bottom sheet
/// (mockup: docs/mockups/snapdrop_qr_help_sheet.html) that explains the QR is
/// generated by the desktop Figma plugin. Dismissed by "Got it", the scrim, or
/// the back gesture. Mirrors correctly under RTL.
Future<void> showQrHelpSheet(BuildContext context) {
  return showModalBottomSheet<void>(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    barrierColor: const Color(0xFF040A07).withValues(alpha: 0.62),
    builder: (_) => const QrHelpSheet(),
  );
}

class QrHelpSheet extends StatelessWidget {
  const QrHelpSheet({super.key});

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    return SafeArea(
      top: false,
      child: Container(
        width: double.infinity,
        decoration: const BoxDecoration(
          color: Color(0xFF183121),
          borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
          border: Border(
            top: BorderSide(color: Color(0x24FFFFFF)),
          ),
        ),
        padding: const EdgeInsets.fromLTRB(24, 12, 24, 30),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // grabber
            Center(
              child: Container(
                width: 40,
                height: 4,
                margin: const EdgeInsets.only(bottom: 20),
                decoration: BoxDecoration(
                  color: Colors.white.withValues(alpha: 0.22),
                  borderRadius: BorderRadius.circular(999),
                ),
              ),
            ),
            Text(
              l10n.qr_help_title,
              textAlign: TextAlign.center,
              style: const TextStyle(
                fontFamily: 'Inter',
                color: Colors.white,
                fontSize: 20,
                fontWeight: FontWeight.w700,
                letterSpacing: -0.1,
              ),
            ),
            const SizedBox(height: 22),
            _step(1, l10n.qr_help_step1),
            const SizedBox(height: 15),
            _step(2, l10n.qr_help_step2),
            const SizedBox(height: 15),
            _step(3, l10n.qr_help_step3),
            const SizedBox(height: 20),
            _note(l10n.qr_help_note),
            const SizedBox(height: 22),
            SizedBox(
              height: 50,
              child: Material(
                color: Colors.transparent,
                shape: StadiumBorder(
                  side: BorderSide(
                      color: Colors.white.withValues(alpha: 0.14), width: 1),
                ),
                clipBehavior: Clip.antiAlias,
                child: InkWell(
                  onTap: () => Navigator.of(context).pop(),
                  child: Center(
                    child: Text(
                      l10n.qr_help_dismiss,
                      style: const TextStyle(
                        fontFamily: 'Inter',
                        color: Colors.white,
                        fontSize: 15,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _step(int n, String text) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        StepBadge(n, size: 27),
        const SizedBox(width: 13),
        Expanded(
          child: Padding(
            padding: const EdgeInsets.only(top: 3),
            child: Text(
              text,
              textAlign: TextAlign.start,
              style: const TextStyle(
                fontFamily: 'Inter',
                color: ThemeConstant.muted,
                fontSize: 14,
                height: 1.4,
                fontWeight: FontWeight.w400,
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _note(String text) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.only(top: 1),
          child: Icon(Icons.info_outline_rounded,
              size: 14, color: Colors.white.withValues(alpha: 0.5)),
        ),
        const SizedBox(width: 8),
        Expanded(
          child: Text(
            text,
            textAlign: TextAlign.start,
            style: const TextStyle(
              fontFamily: 'Inter',
              color: Color(0xFF93A79C),
              fontSize: 11.5,
              height: 1.45,
              fontWeight: FontWeight.w400,
            ),
          ),
        ),
      ],
    );
  }
}
