// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get app_share_dialog_text_1 => 'Share Snapdrop with Your Colleagues';

  @override
  String get app_share_dialog_text_2 =>
      'You\'ve successfully shared images 3 times. Spread the word about Snapdrop so your colleagues can benefit too!';

  @override
  String get app_share_dialog_share_now_button => 'Share Now';

  @override
  String get app_share_dialog_maybe_later_button => 'Maybe Later';

  @override
  String get app_share_text_1 =>
      '🚀 Discover Snapdrop - the easiest way to transfer images directly to your Figma designs! 🎨\n\n';

  @override
  String get app_share_text_2 =>
      '📲 Download now and streamline your design workflow:\n\n';

  @override
  String get language_selection_herotext_1 => 'Select your';

  @override
  String get language_selection_herotext_2 => 'preferred language';

  @override
  String get language_selection_continue => 'Continue';

  @override
  String get onboard_hero_text_1 => 'Send images';

  @override
  String get onboard_hero_text_2 => 'straight to Figma';

  @override
  String get onboard_subline => 'Phone to canvas, in seconds.';

  @override
  String get onboard_step_1 => 'Pick up to 10 images from your phone';

  @override
  String get onboard_step_2 => 'Scan the QR in your Figma plugin';

  @override
  String get onboard_step_3 => 'They land straight on your canvas';

  @override
  String get onboard_button_text => 'Get Started';

  @override
  String get onboarding_title => 'Send photos straight into Figma';

  @override
  String get onboarding_subtitle =>
      'Snapdrop pushes images from your phone into your Figma canvas — through the desktop plugin.';

  @override
  String get onboarding_step1_title =>
      'Open Snapdrop in Figma on your computer';

  @override
  String get onboarding_step1_desc =>
      'The desktop plugin shows a QR code on your screen.';

  @override
  String get onboarding_step2_title => 'Pick your photos, then scan that QR';

  @override
  String get onboarding_step2_desc =>
      'Point your phone at the code to connect.';

  @override
  String get onboarding_step3_title => 'Your photos drop into Figma';

  @override
  String get onboarding_step3_desc =>
      'They appear in your canvas, ready to use.';

  @override
  String get onboarding_note =>
      'The QR code comes from the desktop Figma plugin — not this app, and not Figma mobile.';

  @override
  String get onboarding_cta => 'Get Started';

  @override
  String get scan_subtitle => 'Point at the code from your Figma plugin';

  @override
  String get scan_help_link => 'Where\'s the QR code?';

  @override
  String get qr_help_title => 'Where\'s the QR code?';

  @override
  String get qr_help_step1 => 'Open Figma on your desktop computer.';

  @override
  String get qr_help_step2 =>
      'Run the Snapdrop plugin — Menu > Plugins, or search \"Snapdrop\".';

  @override
  String get qr_help_step3 => 'A QR code appears. Point your phone at it.';

  @override
  String get qr_help_note =>
      'It must be desktop Figma. The code is generated by the plugin, not this app.';

  @override
  String get qr_help_dismiss => 'Got it';

  @override
  String get showcase_one_title => 'Dropdown Button';

  @override
  String get showcase_one_subtitle =>
      'Select albums you want to choose photos from';

  @override
  String get showcase_two_title => 'Select Images';

  @override
  String get showcase_two_subtitle => 'Select images you want to share';

  @override
  String get showcase_three_title => 'Connect Button';

  @override
  String get showcase_three_subtitle => 'Proceed to the next step';

  @override
  String get home_screen_herotext_1 => 'Select Images';

  @override
  String get home_screen_herotext_2 => 'to continue';

  @override
  String get home_screen_herotext_3 => 'Upto 10 images';

  @override
  String get home_screen_button => 'Connect';

  @override
  String get send_button => 'Send';

  @override
  String get connection_connected => 'Connected';

  @override
  String get connection_not_connected => 'Not connected — scan to connect';

  @override
  String get home_album_view_all => 'View all';

  @override
  String get empty_state_title => 'No images here yet';

  @override
  String get empty_state_body =>
      'Photos in this album will appear here. Try another album above.';

  @override
  String get showcase_four_title => 'QR Scanner';

  @override
  String get showcase_four_subtitle => 'Click to Scan QR Code';

  @override
  String get qr_screen_herotext_1 => 'Select a plugin';

  @override
  String get qr_screen_herotext_2 => 'to continue';

  @override
  String get qr_screen_herotext_3 => 'Scan QR Code to connect';

  @override
  String get qr_timed_out_label => 'Scan timed out';

  @override
  String get qr_timed_out_message =>
      'No QR code scanned — it may have expired.';

  @override
  String get qr_restart_scan => 'Restart Scan';

  @override
  String get no_internet_connection => 'No internet connection';

  @override
  String get connection_lost => 'Connection lost';

  @override
  String get connection_lost_body =>
      'The session dropped. Reconnect to keep sending.';

  @override
  String get reconnect_button => 'Reconnect';

  @override
  String get qr_screen_info_button =>
      'Open Figma -> Design File -> Plugin -> Snapdrop';

  @override
  String get qr_screen_button_scanning => 'Scanning...';

  @override
  String get qr_screen_button_scanning_completed => 'Connected Successfully';

  @override
  String get showcase_five_title => 'Close Button';

  @override
  String get showcase_five_subtitle => 'Exit the Application';

  @override
  String get showcase_six_title => 'Send Button';

  @override
  String get showcase_six_subtitle => 'Send More Images';

  @override
  String get send_screen_hero_text_1 => 'Transferred';

  @override
  String get send_screen_hero_text_2 => 'Images';

  @override
  String get send_screen_transferring => 'Transferring';

  @override
  String get send_screen_complete_1 => 'Transfer';

  @override
  String get send_screen_complete_2 => 'Complete';

  @override
  String get send_screen_connected_to => 'CONNECTED TO';

  @override
  String get send_screen_your_id => 'YOUR ID';

  @override
  String get send_screen_connect_button => 'Click to Send';

  @override
  String get send_screen_close_button => 'Close';

  @override
  String get send_screen_send_more_button => 'Send';

  @override
  String get app_conditions_internet_connection =>
      'Check your Internet Connection and try again!';

  @override
  String get app_conditions_image_selection_limit =>
      'Can Only select upto 10 Images!';

  @override
  String get app_conditions_size_limit => 'File Size Limit Exceded';

  @override
  String get permission_dialog_title => 'Allow photo access';

  @override
  String get permission_dialog_body =>
      'Snapdrop needs your photos to send them to Figma. Nothing leaves your phone until you pick and send.';

  @override
  String get permission_dialog_allow => 'Allow';

  @override
  String get permission_dialog_exit => 'Exit';

  @override
  String get exit_dialog_title => 'Leave Snapdrop?';

  @override
  String get exit_dialog_body => 'Your current selection won\'t be saved.';

  @override
  String get exit_dialog_exit => 'Exit';

  @override
  String get exit_dialog_cancel => 'Cancel';

  @override
  String get share_dialog_title => 'Enjoying Snapdrop?';

  @override
  String get share_dialog_body =>
      'If it saved you time, passing it to another designer helps more than you\'d think.';

  @override
  String get share_dialog_share => 'Share';

  @override
  String get share_dialog_maybe_later => 'Maybe later';
}
