name: Flutter CI/CD

on:
  push:
    branches: [ saurabh_dev ]
  pull_request:
    branches: [ saurabh_dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'  # or 3.29.x when fully stable in GitHub Actions

        # ✅ Create .env from GitHub secrets
    - name: Create .env file from secrets
      run: |
        echo "FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }}" >> .env
        echo "FIREBASE_API_KEY_IOS=${{ secrets.FIREBASE_API_KEY_IOS }}" >> .env
        echo "FIREBASE_API_KEY_WEB=${{ secrets.FIREBASE_API_KEY_WEB }}" >> .env
        echo "FIREBASE_API_KEY_MACOS=${{ secrets.FIREBASE_API_KEY_MACOS }}" >> .env
        echo "FIREBASE_API_KEY_WINDOWS=${{ secrets.FIREBASE_API_KEY_WINDOWS }}" >> .env
    
    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    # Optional: Upload artifact
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
